# Generated by Django 2.1.3 on 2022-04-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
