# Generated by Django 2.1.3 on 2022-04-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220420_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pdf',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='key',
        ),
    ]
