# Generated by Django 2.1.3 on 2022-04-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220420_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='books/pdfs/')),
                ('key', models.CharField(max_length=100)),
            ],
        ),
    ]
